# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin('vagrant-linode')

Vagrant.configure('2') do |config|

  config.ssh.username = 'rawrus'
  config.ssh.private_key_path = '~/.ssh/draugr'

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :linode do |provider, override|
    override.vm.box = 'linode'
    override.vm.box_url = 'https://github.com/displague/vagrant-linode/raw/master/box/linode.box'
    provider.token = ENV['LINODE_TOKEN']

    provider.distribution = 'Ubuntu 14.04 LTS'
    provider.ssh_key_name = 'Test Key'
    provider.plan = '1024'

    # Disk Image Sizes (Optional configuration)

    # Main Disk Image Size
    # [str] ( Full Allocation - Swap ) if nil
    provider.xvda_size = '1024'

    # Swap Image Size
    # [str] 256 if nil
    provider.swap_size = '256'

    # Kernel Image ID
    # [str] 138 if nil
    provider.kernel_id = '138'
  end
  


  # Linode Specific Configurations

  ## Each facility gets three different machines - each of them will correspond to a 
  ## specific set of machines.
  ## - Hosts
  ## - Backup Boxes
  ## - Linode's Linodes

  # Atlanta
  config.vm.define :atlanta do |atlanta|
    atlanta.vm.provider :linode do |provider|
      provider.label = 'Atlanta-host-audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'atlanta'
    end
  end

  # Dallas
  config.vm.define :dallas do |dallas|
    dallas.vm.provider :linode do |provider|
      provider.label = 'Dallas-Host-Audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'dallas'
    end
  end
  
  # Fremont
  config.vm.define :fremont do |fremont|
    fremont.vm.provider :linode do |provider|
      provider.label = 'Fremont-Host-Audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'fremont'
    end
  end
  
  # London
  config.vm.define :london do |london|
    london.vm.provider :linode do |provider|
      provider.label = 'London-Host-Audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'london'
    end
  end
  
  # Newark
  config.vm.define :newark do |newark|
    newark.vm.provider :linode do |provider|
      provider.label = 'Newark-Host-Audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'newark'
    end
  end
  
  # Singapore
  config.vm.define :singapore do |singapore|
    singapore.vm.provider :linode do |provider|
      provider.label = 'Singapore-Host-Audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'singapore'
    end
  end
  
  # Tokyo
  config.vm.define :tokyo do |tokyo|
    tokyo.vm.provider :linode do |provider|
      provider.label = 'Tokyo-Host-Audit'
      provider.group = 'Internal-Audit'
      provider.datacenter = 'tokyo'
    end
  end
  
  ### Quick Provisioning via shell script
  config.vm.provision :shell, path: 'scripts/provision.sh'

end
