# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.ssh.username = 'tester'
  config.ssh.private_key_path = './test_id_rsa'

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :linode do |provider, override|
    override.vm.box = 'linode'
    override.vm.box_url = 'https://github.com/displague/vagrant-linode/raw/master/box/linode.box'
    provider.token = ENV['LINODE_TOKEN']
    provider.ssh_key_name = 'Test Key'
    provider.distribution = 'Debian 8'
    provider.datacenter = 'newark'
    provider.plan = '1024'
    provider.label = 'vagrant-'+Time.new.strftime("%F%T").gsub(/[^0-9]/,'')

    # Disk Image Sizes (Optional configuration)

    # Main Disk Image Size
    # [str] ( Full Allocation - Swap ) if nil
    provider.xvda_size = '2048'

    # Swap Image Size
    # [str] 256 if nil
    provider.swap_size = '256'

    # Kernel Image ID
    # [str] 138 if nil
    # provider.kernel_id = '138'
    provider.kernel = 'Latest 64 bit'

    # Networking (Optional Configuration)

    # Enable private networking
    # [boolean] disabled if nil
    #provider.private_networking = true
  end

  config.vm.provision :shell, path: 'scripts/provision.sh'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'cookbooks'
    chef.add_recipe 'test'
  end

  # Linode Specific Configurations
  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.provider :linode do |provider|
      provider.distribution = 'Ubuntu 14.04 LTS'

      # Optional Settings
      provider.label = 'Vagrant-Ubuntu'
    end
  end

  config.vm.define :centos do |centos|
    centos.vm.provider :linode do |provider|
      provider.distribution = 'CentOS 7'
    end
  end
end
