Vagrant.require_plugin('vagrant-linode')
Vagrant.require_plugin('vagrant-omnibus')

Vagrant.configure('2') do |config|
  config.omnibus.chef_version = :latest

  config.ssh.username = 'tester'
  config.ssh.private_key_path = './test_id_rsa'

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :linode do |provider, override|
    override.vm.box = 'linode'
    override.vm.box_url = 'https://github.com/displague/vagrant-linode/raw/master/box/linode.box'
    provider.token = ENV['LINODE_TOKEN']
    provider.ssh_key_name = 'Test Key'
    provider.image = 'Ubuntu 14.04 x64'
    provider.datacenter = 'newark'
    provider.plan = '1024'
  end

  config.vm.provision :shell, path: 'scripts/provision.sh'

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'cookbooks'
    chef.add_recipe 'test'
  end

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.provider :linode do |provider|
      provider.image = 'Ubuntu 14.04 x64'
    end
  end

  config.vm.define :centos do |centos|
    centos.vm.provider :linode do |provider|
      provider.image = 'CentOS 7'
    end
  end
end
