# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :linode do |linode|
    linode.datacenter = "dallas"
    linode.plan = "Linode 1024"
    linode.distribution = "Ubuntu 14.04 LTS"
  end
end
